<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG1BOpuR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG1BOpuR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG1BOpuR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG1BOpuR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG1BOpuR\App_KernelDevDebugContainer([
    'container.build_hash' => 'G1BOpuR',
    'container.build_id' => '254eb74d',
    'container.build_time' => 1758580625,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG1BOpuR');
