<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdsxqJh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdsxqJh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRdsxqJh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRdsxqJh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRdsxqJh\App_KernelDevDebugContainer([
    'container.build_hash' => 'RdsxqJh',
    'container.build_id' => '8162397b',
    'container.build_time' => 1758581011,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRdsxqJh');
