nelmio_cors:
    defaults:
        allow_credentials: true          # Autoriser les cookies et l'authentification
        allow_origin: ['http://localhost:8080']  # Ton front
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']         # Optionnel : pour certains headers exposés
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8080']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            expose_headers: ['Link']
            max_age: 3600
