version: "3.9"

services:
  # FRONT-END
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:80"   
    depends_on:
      - backend-nginx
    networks:
      - app

  # BACKEND PHP (Symfony)
  backend-php:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end/app:/var/www/html
    environment:
      APP_ENV: dev
    networks:
      - app

  # BACKEND NGINX
  backend-nginx:
    image: nginx:alpine
    volumes:
      - ./back-end/app:/var/www/html:ro
      - ./back-end/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"  
    depends_on:
      - backend-php
    networks:
      - app

  # DATABASE (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app

  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"  
    depends_on:
      - db
    networks:
      - app

networks:
  app:

volumes:
  db_data:
