services:
  php-fpm:
    build:
      context: ./back-end/app
      dockerfile: ../Dockerfile
    container_name: ecoride-php-fpm
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      APP_TRUSTED_HOSTS: ${APP_TRUSTED_HOSTS}
      DATABASE_URL: ${DATABASE_URL}
      MONGODB_URL: ${MONGODB_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
    volumes:
      - ./back-end/app:/var/www/html:cached
      - php_var:/var/www/html/var
      - php_vendor:/var/www/html/vendor
    depends_on:
      - mysql_db
      - mongo
    restart: unless-stopped

  nginx-backend:
    image: nginx:alpine
    container_name: ecoride-nginx-backend
    ports:
      - "8000:80" # Backend Symfony accessible sur http://localhost:8000
    volumes:
      - ./back-end/app:/var/www/html:cached
      - ./back-end/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    restart: unless-stopped

  mysql_db:
    image: mysql:8.0
    container_name: ecoride-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: ecoride-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo_express:
    image: mongo-express:1.0.0
    container_name: ecoride-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: ecoride-frontend
    ports:
      - "8080:80" # Front accessible sur http://localhost:8080
    depends_on:
      - nginx-backend
    restart: unless-stopped
    volumes:
      - ./front-end:/usr/share/nginx/html:cached
      - ./front-end/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecoride-phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql_db
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data:
  php_var:
  php_vendor:
