version: "3.9"

services:
  php-fpm:
    build:
      context: ./back-end/app
      dockerfile: ../Dockerfile
    container_name: ecoride-php-fpm
    environment:
      APP_ENV: prod
      DATABASE_URL: "mysql://anastasia:OneLove24!@mysql_db:3306/ecoride?serverVersion=8.0&charset=utf8mb4"
      MONGODB_URL: "mongodb://mongo_user:mongo_password@mongo:27017/ecoride_mongo"
    volumes:
      - ./back-end/app:/var/www/html:cached
      - php_var:/var/www/html/var
      - php_vendor:/var/www/html/vendor
    depends_on:
      - mysql_db
      - mongo
    restart: unless-stopped

  mysql_db:
    image: mysql:8.0
    container_name: ecoride-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: anastasia
      MYSQL_PASSWORD: OneLove24!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: ecoride-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: ecoride-frontend
    ports:
      - "8080:80"   # Nginx exposé sur localhost:8080
    depends_on:
      - php-fpm
    restart: unless-stopped
    volumes:
      - ./front-end:/usr/share/nginx/html:cached
      - ./front-end/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

volumes:
  mysql_data:
  mongo_data:
  php_var:
  php_vendor:
